import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/sidebar";
import { Popup } from "@/components/task/popup";
import TaskContextProvider from "@/hooks/useTask";

const jetBrainsMono = localFont({
  src: "./fonts/woff/JetBrainsMono-Regular.woff",
  variable: "--font-jetBrains-mono",
  weight: "100 900",
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <TaskContextProvider>
          <SideBar />
          <Popup />
          {children}
        </TaskContextProvider>

      </body>
    </html>
  );
}
