import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/sidebar";
import { Popup } from "@/components/task/popup";
import TaskContextProvider from "@/hooks/useTask";
import React from "react";

const jetBrainsMono = localFont({
  src: "./fonts/woff/JetBrainsMono-Regular.woff",
  variable: "--font-jetBrains-mono",
  weight: "100 900",
})

const jetBrainsMonoBold = localFont({
  src: "./fonts/woff/JetBrainsMono-Bold.woff",
  variable: "--font-jetBrainsBold-mono",
  weight: "100 900",
})

const jetBrainsMonoExtraBold = localFont({
  src: "./fonts/woff/JetBrainsMono-ExtraBold.woff",
  variable: "--font-jetBrainsExtraBold-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} ${jetBrainsMonoBold.variable} ${jetBrainsMonoExtraBold.variable} antialiased`}
      >
        <TaskContextProvider>
          <SideBar />
          <Popup />
          {children}
        </TaskContextProvider>

      </body>
    </html>
  );
}
